// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wbaqfpamfhmdkmevtwlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiYXFmcGFtZmhtZGttZXZ0d2xvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzOTkwMzEsImV4cCI6MjA4MDk3NTAzMX0.pIhdBSjdlYaEGVJBku40xiSOWiyGG8R4vdt9S76iRco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});